### ISSUE TITLE
Textfilter wird nicht ausgewertet

### ISSUE THREAD

**Issue by bibib** [MetaModels/filter_text#10]
Contao 3.3.5
metamodels/core dev-tng

Ich habe ein Attribut "longtext" erstellt, einen Textfilter für dieses Attribut angelegt, im Frontendfilter diesen als anzuwendenden Filtereinstellungen angegeben, ebenso in der MetaModel-Liste. Wenn ich nun ein Suchwort in die Maske eingebe, tut sich genau gar nichts, die Seite lädt neu, das Suchwort bleibt im Eingabefeld stehen und es wird kein Beitrag rausgefiltert.

Genaue Beschreibung siehe [hier] (https://community.contao.org/de/showthread.php?54590-Textfilter-funktioniert-nicht&p=352253&viewfull=1#post352253)

**Comment by cboelter** [comment]
Der Fehler sollte jetzt eigentlich behoben sein. Einmal aktualisieren und danach das FrontendFilter-Contentelement einmal neu abspeichern.

**Comment by bibib** [comment]
Fehler besteht leider weiterhin. Ich habe meine Pakete einmal aktualisiert (metamodels/core dev-tng (627e4d39) und metamodels/bundle_all 1.0.1), Systemwartung gemacht, Cache gelöscht, bringt aber nichts. Muss ich irgendwie einen neuen Textfilter installieren?

**Comment by cboelter** [comment]
Hast Du auch das Inhaltselement (MetaModels-Frontendfilter) im Artikel neu gespeichert?

**Comment by bibib** [comment]
Ja, habe ich. Und zusätzlich zum Inhaltselement habe ich auch das Modul MetaModels-Frontendfilter probiert. Beides erfolglos.

**Comment by cboelter** [comment]
Wie ist denn die genaue Konfiguration sind filter und die zielliste auf einer Seite?

**Comment by bibib** [comment]
Ja, sind sie.

**Comment by discordier** [comment]
Habe den Filter eben auf einer meiner installationen eingerichtet und er tut tadellos.

**Comment by bibib** [comment]
Dann muss das Problem vor dem Monitor sitzen :(

**Comment by discordier** [comment]
die bundle version stimmt.
Beim filter solltest du hash 6df9de1f2e7429455a7c270bcc511fedaae8fc04 haben.

**Comment by bibib** [comment]
Okay, eventuell kommen wir der Sache näher. Ich Dummy dachte, eine Paketaktualisierung im Composer reicht.

Nun habe ich den Textfilter extra aktualisiert. So schaut's aus:
![mm_composer](https://cloud.githubusercontent.com/assets/3650034/5724468/0ba9e8ee-9b4c-11e4-8a64-f62dd9896537.JPG)

Ist das jetzt korrekt? Wahrscheinlich nicht, ich habe nochmal das Inhaltselement mit dem MetaModel-Frontend-Filter neu abgespeichert, aber es geht immer noch nicht.

**Comment by bibib** [comment]
Super, aus Jux und Tollerei auf "Pakete aktualisieren" geklickt und damit alles kaputt gemacht:
Bekomme nun folgende Fehlermeldung:
```Warning: array_merge(): Argument #2 is not an array in composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php on line 289

#0 [internal function]: __error(2, 'array_merge(): ...', '/kunden/299112_...', 289, Array)
#1 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(289): array_merge(Array, NULL)
#2 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(333): DependencyInjection\Container\ContainerInitializer->provideSingletons(Object(Pimple))
#3 system/initialize.php(244): DependencyInjection\Container\ContainerInitializer->init()
#4 contao/preview.php(24): require('/kunden/299112_...')
#5 {main}```

Diese Versionen sind jetzt installiert:
![mm_composer_19](https://cloud.githubusercontent.com/assets/3650034/5802206/10e04fa0-9ff3-11e4-894d-0338a0deb8ed.JPG)

**Comment by cboelter** [comment]
Ja bist Du nicht die einzige mit: https://github.com/contao-community-alliance/dependency-container/issues/9 Dort ist auch ein "quickfix" mit drin.

**Comment by bibib** [comment]
Danke, und wo muss das hin?

**Comment by cboelter** [comment]
Dort composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php on line 289

**Comment by discordier** [comment]
Wurde als https://github.com/contao-community-alliance/dependency-container/releases/tag/1.7.1 released, sollte also alles wieder funktionieren.

**Comment by bibib** [comment]
Hm, aber der Filter tut immer noch nicht. Sicher die Version 1.7.1? Die lässt sich bei mir gar nicht installieren, ich hab immer noch die 1.7.2 drin, selbst wenn ich den dependency-container ganz deinstalliere und ihn in der Version 1.7.1 wieder zum installieren auswähle.

**Comment by discordier** [comment]
Sorry, mein Fehler, sollte heissen "ab 1.7.1".

Auf der von dir verlinkten Seite sehe ich gar keinen Textfilter mehr.

**Comment by bibib** [comment]
Sorry, hab ihn wieder reingegeben. Da inzwischen ja der Textcombine-Filter läuft, und dieser hier besser geeignet ist, verwende ich diesen, aber interessant wäre ja trotzdem, warum der Textfilter nicht geht. Zur Zeit sind noch wenige Suchworte drin, aber auf "Grieche", "griechisch", "Moussaka", "Souvlaki" sollte er anspringen.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@bibib could you please have a final look at this and tell if your issue has been resolved?
