### ISSUE TITLE
Zwei Begriffe suchen hat Probleme mit der Reihenfolge

### ISSUE THREAD

**Issue by MacKP** [MetaModels/filter_text#13]
Im Text (Ein Attribut) stehen zwei Worte in der Reihenfolge 'a b'.
Gesucht wird nach 'b a' -> Ergebniss: nichts
Gesucht wird nach 'a b' -> Ergebniss: Das Item wird gefunden

Erwartetes Verhalten: Bei beiden Suchen würde ich erwarten das Item zu finden. Wörter die durch ein Leerzeichen getrennt sind, sollten also ohne Reihenfolge gesucht werden (bei Ungenauer Suche).

Viele Grüße

**Comment by xantippe** [comment]
@MacKP die "Suche" ist die "Standard-MySQL-Filterung nur eben mit oder ohne "%"

siehe https://github.com/MetaModels/filter_text/blob/master/src/MetaModels/Filter/Setting/Text.php#L98-L110

**Comment by MacKP** [comment]
Dann müßte also der String, der gesucht werden soll vorher erst auseinander genommen werden, damit nach den einzelnen Worten gesucht wird. Ist zwar mehr Aufwand aber wäre ein Möglichkeit das zu machen.

**Comment by xantippe** [comment]
korrekt - in MM ist keine "echte Suchmaschine" eingebaut - hier wird "on the fly" die Tabelle durchsucht

das kannst Du also selbst in phpMyAdmin austesten

```SELECT * FROM mytable WHERE mystring LIKE '%dies% OR LIKE '%das%'```

**Comment by xantippe** [comment]
workaround:
```SELECT * FROM mytable WHERE mystring {{file::mylike.php}}```

mylike.php => GET-Input splitten und in einer Schleife ```LIKE '%'.%item[i].'% OR...``` machen

**Comment by xantippe** [comment]
der PR https://github.com/MetaModels/filter_text/pull/22 sollte Dein Problem lösen - hier ist eine http://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html eingebaut (soweit ich das am Quelltext gesehen habe)

**Comment by zonky2** [comment]
der Branch https://github.com/MetaModels/filter_text/tree/feature/extended-search fixt das Problem

**Comment by discordier** [comment]
Den muss @stefanheimes aber noch abschliessen und dann mergen.

**Comment by zonky2** [comment]
heute Abend ;-)

**Comment by zonky2** [comment]
impelemtiert https://github.com/MetaModels/filter_text/releases/tag/2.0.0-alpha5
