### ISSUE TITLE
404 - Not found - wenn Suchbegriff mit / eingegeben wird

### ISSUE THREAD

**Issue by mcfausti** [MetaModels/filter_text#15]
Wenn im Suchfeld ein Suchbegriff mit einem / eingegeben wird, dann bekomme ich eine 404 - Not found - Fehlermeldung.

URL schaut dann folgendermaßen aus:
...../textsearch_5/29548%2F6.html

Suchbegriff war: 29548/6

Not Found

The requested URL /objekt-suche/textsearch_5/29548/6.html was not found on this server.

Laut zonky im Contao-Forum sollte ich
../objekt-suche.html?textsearch_5=29548/6
ausprobieren.

Diese Variante funktioniert und liefert Suchergebnisse zurück.

Der passende Thread im Contao-Forum:
https://community.contao.org/de/showthread.php?54128-MetaModels-Filter-Mehrfachauswahl-Sonderzeichen

LG

**Comment by discordier** [comment]
The problem is already in the core.
The removal of the encoding of slash and apos in https://github.com/MetaModels/core/commit/068f79e1d86932e09df0105adff19ac1afe998df (see MetaModels/core#814) most likely broke this.

**Comment by discordier** [comment]
Ref: MetaModels/core#139

**Comment by mecintosch** [comment]
In meiner Mehrfachauswahl stehen Werte die ua. Klammern und Schrägstriche enthalten. Leider wird mir bei Auswahl von Begriffen mit / ( ) eine 404 angezeigt. 

Gibt es da eventuell schon eine Lösung?

**Comment by discordier** [comment]
When using a proper alias column, this problem should not occur.
This is the only work around currently, sorry.

**Comment by mecintosch** [comment]
Leider weiß ich nicht genau wie ich da jetzt weitermache.
Habe ein neues Alias Feld angelegt, das sich automatisch mit dem Filter-Wert befüllt (die Schrägstriche und Klammern sind weg). Aber wie verknüpfe ich diese jetzt damit im Filter der richtige Wert steht und nur die URL aus dem Alias erzeugt wird (URL-Parameter?).

Oder bin ich ganz auf dem Holzweg und kann ich nur das eigentliche Text Attribut zu einem Alias Attribut umwandeln? Dann verliere ich aber auch alle Leerzeichen und die Groß/Kleinschreibung.

**Comment by zonky2** [comment]
hmmm... so als Idee:
* eigenes Filter-Template bauen
* Filter auf Alias legen
* im Template die "Labels" auf das Textfeld umbiegen

**Comment by mecintosch** [comment]
Ich denke das Problem wird irgendwann behoben?
In der Zwischenzeit ersetze ich meine / mit | und aus den ( ) werden [ ].

**Comment by zonky2** [comment]
hast Du die Variante mit einem eigenen Filtertemplate probiert?

**Comment by mecintosch** [comment]
Habe ich nicht probiert, brauchte eine schnelle Lösung.

**Comment by zonky2** [comment]
folgendes kann probiert werden (1. und 2. ändern)

1:
https://github.com/MetaModels/core/blob/master/src/MetaModels/FrontendIntegration/FrontendFilter.php#L116

```diff
                $strFilterAction .= sprintf(
                    $GLOBALS['TL_CONFIG']['disableAlias'] ? '&amp;%s=%s' : '/%s/%s',
                    $strName,
-                    rawurlencode($strValue)
+                   rawurlencode(rawurlencode($strValue))
                );
```

2.
https://github.com/MetaModels/core/blob/master/src/MetaModels/FrontendIntegration/HybridList.php#L73
```diff
            if (is_string($varValue)) {
-                $arrReturn[$strName] = rawurldecode($varValue);
+                $arrReturn[$strName] = $varValue;
            }
```

damit können Texte mit / oder + gesucht werden

**Comment by zonky2** [comment]
pls test PR https://github.com/MetaModels/core/pull/1027

**Comment by discordier** [comment]
Closed in favor of MetaModels/core#1033
