### ISSUE TITLE
Bei Filterregel im BE fehlt das Icon in Filterregel-Auflistung

### ISSUE THREAD

**Issue by xantippe** [MetaModels/filter_text#17]
Bei Filterregel im BE fehlt das Icon in Filterregel-Auflistung

TNG 22.11.2015

**Comment by xantippe** [comment]
die .htaccess fehlt in /html

**Comment by xantippe** [comment]
https://github.com/MetaModels/filter_text/pull/18

**Comment by discordier** [comment]
Had been fixed in #21
