### ISSUE TITLE
Wrong labels in the GUI filter config

### ISSUE THREAD

**Issue by binron** [MetaModels/filter_text#36]
any = suche einige Wörter (ODER)
all = suche alle Wörter (UND)

<img width="517" alt="screen shot 2018-04-24 at 11 47 13" src="https://user-images.githubusercontent.com/3243377/39180815-2d50a9f8-47b8-11e8-90f4-69369cdd5afb.png">

**Comment by zonky2** [comment]
Thx! fixed in https://www.transifex.com/metamodels/metamodels/translate/#de/filter_text-tl_metamodel_filtersetting

update after next tagging
