### ISSUE TITLE
Textfilter filtert nicht mehr sobald in der MM-Frontendliste das Rendertemplate geändert wird

### ISSUE THREAD

**Issue by MaryLou1** [MetaModels/filter_text#5]
Ich weiß nicht, ob's hierher gehört, aber ist mir beim Testen aufgefallen:

Habe einen Textfilter erstellt --> Ausgabe im FE über ein Modul MM-Frontendfilter --> Ausgabe im FE über ein Modul MM-Liste: Filter funktioniert einwandfrei, doch sobald ein anderes Renderingtemplate ausgewählt wird (unter "Anzuwendende Renderingeinstellungen"), funktioniert der Filter nicht mehr, sondern es werden alle Datensätze ausgegeben. Bei anderen Filtern, wie "Einzelauswahl" oder "Mehrfachauswahl" bereitet eine Änderung des Rendertemplates keine Probleme.

Contao 2.11.16, aktuelle MM-Nightly

**Comment by MacKP** [comment]
Die aktuelle Nightly wird doch gar nicht mehr für Contao 2.11 entwickelt? Bitte das Ticket noch mal öffnen, wenn sich das in einer Contao 3.2 (oder höher) nachstellen lässt.
