### ISSUE TITLE
Mehrere Felder mittels Combined Values durchsuchen

### ISSUE THREAD

**Issue by emkayy** [MetaModels/filter_text#7]
Mit dem Textfilter lässt sich aktuell nicht das Attribut "Kombinierte Einträge" durchsuchen. Das wird in der DB aber auch nur als String / "Textfeld" abgelegt.

So könnte man sich ganz einfach seinen eigenen Suchindex aufbauen. Wäre vermutlich auch performanter als zur Laufzeit verschiedene Felder in der DB zu durchsuchen.

Dazu müsste man nur in der config.php eine Zeile ergänzen:

https://github.com/MetaModels/filter_text/blob/contao3/src/system/modules/metamodelsfilter_text/config/config.php

```$GLOBALS['METAMODELS']['filters']['text']['attr_filter'][] = 'combinedvalues';```

**Comment by MacKP** [comment]
Fixed in 3dbdf13 could you test it.

**Comment by emkayy** [comment]
I would really like to test it. However, if I update now, I know that there will be a hundret things not working anymore. Maybe someone else could quickly test it on a test-installation - which I currently don't have. Sorry!

**Comment by MacKP** [comment]
OK, then I will close this issue. Works for me fine ;-)
