### ISSUE TITLE
Filter nach 0

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/filter_text#8]
Es scheint so das der Filter einen Wert "0" nicht richtig versteht. Es wird der Parameter nicht als Get angehängt. Es scheint so das die 0 als null interpretiert wird. Vieleicht haben wir iwo ein empty ?

**Comment by xantippe** [comment]
getestet Contao 3.5.6 und MM core 2.0.0-alpha8

```\Input::get('test')``` fischt sowohl test=0 als auch test/0 raus - würde somit nur noch POST (oder was anderes) in Frage kommen

**Comment by zonky2** [comment]
am Contao-Core liegt es nicht...
wenn bei den Methoden doSimpleSearch und doComplexSearch folgendes geändert wird

https://github.com/MetaModels/filter_text/blob/master/src/MetaModels/Filter/Setting/Text.php#L122
```diff
-if ($objAttribute && $strParamName && $strParamValue) {
+if ($objAttribute && $strParamName && $strParamValue !== null) {
```
und
https://github.com/MetaModels/filter_text/blob/master/src/MetaModels/Filter/Setting/Text.php#L167
```diff
-if ($objAttribute && $strParamName && $strParamValue && $parentFilter) {
+if ($objAttribute && $strParamName && $strParamValue !== null && $parentFilter) {
```
dann wird mit der direkten Eingabe der Filterung in der URL korrekt nach ```0``` gefiltert z.B.
```/metamodels/mitarbeiterliste-mein-erstes-metamodel-v2/name/0.html```

offensichtlich wird die ```0``` noch bei der Umwandlung der POST-Parameter des Filters in die ULR abgefangen

**Comment by zonky2** [comment]
@stefanheimes pls test

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?
